import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="px-4 mt-4 flex justify-between gap-4 items-center">
          <div className="relative h-[10vh] w-[20vw] max-w-[200px]">
            <Image
              src={
                "https://capzula.com/wp-content/uploads/2023/09/N0nQGy1vPm8uWXG5.svg"
              }
              alt={"logo"}
              fill
            />
          </div>
          <input
            type="text"
            placeholder="Search for products"
            className="w-full px-3 border h-10 rounded-lg max-w-[200px] lg:max-w-4xl shadow-md"
          />
          <div className="lg:flex items-center gap-2 hidden">
            <Link
              href={"https://capzula.com/my-account/"}
              className="font-semibold px-4 py-2 border border-black rounded-md"
            >
              LOGIN
            </Link>
            <Link
              href={"https://capzula.com/register/"}
              className="font-semibold text-white px-4 py-2 bg-black rounded-md"
            >
              REGISTER
            </Link>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
